server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA — fall back to index.html for all non-file routes
    location / {
        try_files $uri $uri/ /index.html;
    }

}
