name: e2e tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # services:
    #   mongo:
    #     image: mongo:latest
    #     ports:
    #       - 27017:27017

    steps:
      # # Backend Setup
      # - name: Checkout Repository
      #   uses: actions/checkout@v3

      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: '11'

      # - name: Start Java Backend
      #   run: |
      #     nohup java -jar backend-latest.jar &
      #     # Kurze Pause, damit sich das Backend initialisieren kann.
      #     sleep 15

      # Frontend Setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node Dependencies
        run: npm install

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Playwright Tests
      - name: Run Playwright Tests
        env:
          FALL_BACKEND: ${{ secrets.FALL_BACKEND }}
          API_AUTH_NAME: ${{ secrets.API_AUTH_NAME }}
          API_AUTH_PWD: ${{ secrets.API_AUTH_PWD }}
          GEOAPIFY_API_KEY: ${{ secrets.GEOAPIFY_API_KEY }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: npx playwright test

      # Upload Playwright Report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
